// Info de pruebas para los usuarios
export const mockUsersData = [
  {
    user: "dmuniz",
    name: "Daniel",
    lastName: "Muniz Turtos",
    privileges: "ROLE_ADMIN",
    state: "Activo",
    area: "INICIO",
  },
  {
    user: "humberto",
    name: "Humberto",
    lastName: "Muniz Martin",
    privileges: "ROLE_ADMIN",
    state: "Activo",
    area: "INICIO",
  },
  {
    user: "yariel",
    name: "Yariel",
    lastName: "Muniz Ferrer",
    privileges: "ROLE_ADMIN",
    state: "Activo",
    area: "INICIO",
  },
  {
    user: "yudi",
    name: "Yudilai",
    lastName: "Muniz Martin",
    privileges: "ROLE_ADMIN",
    state: "Activo",
    area: "INICIO",
  },
  {
    user: "Gemma",
    name: "Gemma",
    lastName: "Anno Lopez",
    privileges: "ROLE_ADMIN",
    state: "Activo",
    area: "INICIO",
  },
  {
    user: "yinet",
    name: "Yinet",
    lastName: "Gonzalez Milian",
    privileges: "ROLE_ADMIN",
    state: "Activo",
    area: "INICIO",
  },
  {
    user: "dmuniz",
    name: "Daniel",
    lastName: "Muniz Turtos",
    privileges: "ROLE_ADMIN",
    state: "Activo",
    area: "INICIO",
  },
  {
    user: "humberto",
    name: "Humberto",
    lastName: "Muniz Martin",
    privileges: "ROLE_ADMIN",
    state: "Activo",
    area: "INICIO",
  },
  {
    user: "yariel",
    name: "Yariel",
    lastName: "Muniz Ferrer",
    privileges: "ROLE_ADMIN",
    state: "Activo",
    area: "INICIO",
  },
  {
    user: "yudi",
    name: "Yudilai",
    lastName: "Muniz Martin",
    privileges: "ROLE_ADMIN",
    state: "Activo",
    area: "INICIO",
  },
  {
    user: "Gemma",
    name: "Gemma",
    lastName: "Anno Lopez",
    privileges: "ROLE_ADMIN",
    state: "Activo",
    area: "INICIO",
  },
  {
    user: "yinet",
    name: "Yinet",
    lastName: "Gonzalez Milian",
    privileges: "ROLE_ADMIN",
    state: "Activo",
    area: "INICIO",
  },
];
